from django.conf.urls import patterns, url

from pdapp import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^wgetallevents/', views.web_getallevents, name = 'wgetallevents'),
    url(r'^wgetevent/(?P<eventid>\d+)/$', views.web_getevent, name='wgetevent'),
    url(r'^wgetevent/(?P<eventid>\d+)/wgetallguests/', views.web_getallguests, name='wgetallguests'),
    url(r'^wgetevent/(?P<eventid>\d+)/wgetallcontacts/', views.web_getallcontacts, name='wgetallcontacts'),
    url(r'^wgetevent/(?P<eventid>\d+)/wgetallnotes/', views.web_getallnotes, name='wgetallnotes'),
    url(r'^wgetevent/(?P<eventid>\d+)/wgetallgifts/', views.web_getallgifts, name='wgetallgifts'),
    url(r'^wgetevent/(?P<eventid>\d+)/wgetwall/', views.web_getwall, name='wgetwall'),
    url(r'^waddevent/', views.web_addevent, name = 'waddevent'),
    url(r'^wremoveevent/', views.web_removeevent, name = 'wremoveevent'),
    url(r'^wgetevent/(?P<eventid>\d+)/waddguest/', views.web_addguest, name='waddguest'),
    url(r'^wgetevent/(?P<eventid>\d+)/wremoveguest/', views.web_removeguest, name='wremoveguest'),
    url(r'^wgetevent/(?P<eventid>\d+)/waddcontact/', views.web_addcontact, name='waddcontact'),
    url(r'^wgetevent/(?P<eventid>\d+)/wremovecontact/', views.web_removecontact, name='wremovecontact'),
    url(r'^wgetevent/(?P<eventid>\d+)/waddnote/', views.web_addnote, name='waddnote'),
    url(r'^wgetevent/(?P<eventid>\d+)/wremovenote/', views.web_removenote, name='wremovenote'),
    url(r'^wgetevent/(?P<eventid>\d+)/waddgift/', views.web_addgift, name='waddgift'),
    url(r'^wgetevent/(?P<eventid>\d+)/wremovegift/', views.web_removegift, name='wremovegift'),
    url(r'^wgetevent/(?P<eventid>\d+)/waddwall/', views.web_addwall, name='waddwall'),
    url(r'^wgetevent/(?P<eventid>\d+)/waddresponse/', views.web_addresponse, name='waddresponse'),
    #url(r'^accounts/login', views.index, name='accountslogin'),
    #url(r'^accounts/logout', views.index, name='account_logout'),

    url(r'^login/', views.android_login, name = 'login'),
    url(r'^checkuser/', views.android_checkuser, name = 'checkuser'),
    #url(r'^updateevent/', views.android_updateevent, name = 'updateevent'),
    url(r'^addevent/', views.android_addevent, name = 'addevent'),
    url(r'^getallevents/', views.android_getallevents, name = 'getallevents'),
    url(r'^addguest/', views.android_addguest, name = 'addguest'),
    url(r'^remove/', views.android_remove, name = 'remove'),
    url(r'^getallguests/', views.android_getallguests, name = 'getallguests'),
    url(r'^addcontact/', views.android_addcontact, name = 'addcontact'),
    url(r'^getallcontacts/', views.android_getallcontacts, name = 'getallcontacts'),
    url(r'^addnote/', views.android_addnote, name = 'addnote'),
    url(r'^getallnotes/', views.android_getallnotes, name = 'getallnotes'),
    url(r'^addgift/', views.android_addgift, name = 'addgift'),
    url(r'^getallgifts/', views.android_getallgifts, name = 'getallgifts'),
    url(r'^addwall/', views.android_addwall, name = 'addwall'),
    url(r'^addresponse/', views.android_addresponse, name = 'addresponse'),
    url(r'^getwall/', views.android_getwall, name = 'getwall'),
    url(r'^gencode/', views.gencode, name = 'gencode'),
    url(r'^guestlogin/', views.android_guestlogin, name = 'guestlogin'),
    url(r'^signupgift/', views.android_signupgift, name = 'signupgift'),
)
